fix: do not hold genesis records in memory
nearprotocol/nearcore pull request #3320
Opened 2020-09-14 23:07 UTC by bowenwang1996

Fixes #3314.

Test plan
---------
* CI tests
* test with a real node to see that memory usage decreases on node start.

2020-09-14 23:48 UTC, SkidanovAlex approved these changes

2020-09-15 13:28 UTC, frol commented on chain/rosetta-rpc/src/lib.rs
> +    genesis_config: GenesisConfig,
Let's keep `Arc<Genesis>` here. Rosetta is optional, and disabled by default, and it is a trade-off we are willing to take for it. Rosetta exposes genesis records as a fake first block, so it needs those records.

2020-09-15 17:59 UTC, bowenwang1996 commented on neard/src/config.rs
> +    pub genesis: Genesis,
It seems to me that `NearConfig` is not really held in memory. `start_with_config` should drop it at the end. Did I miss something here?

2020-09-15 20:00 UTC, frol commented on neard/src/config.rs
> +    pub genesis: Genesis,
I missed the fact that it is dropped. If that is the case, we are good

2020-09-15 20:04 UTC, frol commented
I don’t believe the code with this change can be compiled with `rosetta_rpc` feature enabled. @chefsale  can we test compilation with all the features enabled? (Add a job to do `cargo check --all-features`)

2020-09-15 23:46 UTC, bowenwang1996 commented
> I don’t believe the code with this change can be compiled with rosetta_rpc feature enabled. @chefsale can we test compilation with all the features enabled? (Add a job to do cargo check --all-features)

Why do you think so? CI has the following check
```
cargo check --all --tests --benches --all-features
```

2020-09-16 18:37 UTC, frol approved these changes
The plan LGTM, please, make sure that rosetta RPC is compilable.

2020-09-16 20:44 UTC, nearmax requested changes
Rosetta still seems to be keeping a copy of the genesis records here: https://github.com/nearprotocol/nearcore/blob/38175236f65b3efa675fb2f68ab0a4a1317cbf39/chain/rosetta-rpc/src/lib.rs#L703

In general, it was difficult to verify that no actor actually stores a copy of the genesis or genesis records for itself locally, since there is a lot of cloning. I am not suggesting to make any changes now, but in general we should start thinking about leveraging the strong-typeness of Rust like me, @frol , and @evgenykuzyakov discussed. For instance in this case we could declare records `!Clone` like here
https://doc.rust-lang.org/src/core/clone.rs.html#234 To make sure the code needs to explicitly opt in into cloning.

2020-09-16 20:45 UTC, bowenwang1996 commented
@nearmax @frol explicitly requested that we keep this copy when rosetta is enabled https://github.com/nearprotocol/nearcore/pull/3320#discussion_r488666710

2020-09-16 20:46 UTC, nearmax approved these changes

2020-09-16 21:47 UTC, merged